# Exercise: NumPy

In [1]:
import numpy as np

In [4]:
# Q0. consider the following nd-array:
arr = np.array( [
    [ 1, 2, 3],
    [ 4, 2, 5]] )
# what is the item at index: [1, 0]?

# find out each of the following:-
# dimensions? number of axes
# answer: 2
arr.ndim

# shape?
# answer: (2, 3)

# size?
# answer: 2*3 = 6

# data types stored?
# answer: int32
print(arr.dtype)

# item size?
# answer: 32 / 8 = 4 bytes
print(arr.itemsize)

# what is the item at index: [1, 0]?
# answer: 

int32
4


In [7]:
# Q1. reshape this 1D array into a 2D array of size (2, 5) (print the result)
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array.reshape(2, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
# Q2. reshape this 2D array into a 1D array of size 9 (print the result)
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array.reshape(-1))

[1 2 3 4 5 6 7 8 9]


In [11]:
# Q3. flatten this 3D array into a 1D array (print the result)
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
# Q4. split this 1D array into two subarrays of size 5 (print the result)
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.array_split(array, 2)
# print(np.split(array, 2, axis=0))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [40]:
my_list1 = [1, 2, 3, ['a']]
my_list2 = my_list1[:]
print(my_list2)
my_list1[3][0] = 'b'
print(my_list2)

[1, 2, 3, ['a']]
[1, 2, 3, ['b']]


In [31]:
my_list2[0] = 44
print(my_list1)
print(my_list2)

[1, 2, 3]
[44, 2, 3]


In [42]:
# Q5.1 what is the output of the following code?
a = np.array([1, 2, 3])
b = a[:]

b[0] = 4

print(a) # <-- explain why.

[4 2 3]


In [43]:
# Q5.2 compare the result with this

a = [1, 2, 3] # <-- just a list
b = a[:]

b[0] = 4

print(a)

[1, 2, 3]


In [46]:
# Q6. stack the following two 1D arrays such that the output is
# horizontally stacked: [1, 2, 3, 4, 5, 6]
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

In [47]:
# Q7. stack the following two 1D arrays such that the output is
# vertically stacked: [[1, 2, 3], [4, 5, 6]]
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack([a, b])


array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
# Q8. sort the following array
a = np.array([3, 2, 1, 4, 5])
a.sort()
print(a[::-1])

[5 4 3 2 1]


In [63]:
# Q9. use `np.where()` to find the indices of all elements in the array that are greater than 3.
a = np.array([10, 20, 30, 40, 50])
idx = np.where(a > 30)
print(idx)
print(a[idx])

(array([3, 4], dtype=int64),)
[40 50]


In [64]:
# Q10 Consider the following ndarray:
arr = np.array([[4, 3, 2], [10, 1, 0], [5, 8, 24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [70]:
# Q10-1. Calculate the mean and std of values on the entire array
print('mean:', arr.mean())

# Q10-2. Calculate the mean and std across the vertical axis
print(arr.std(axis=0))

# Q10-3. Calculate the mean and std across the horizontal axis
print(arr.mean(axis=1))

mean: 6.333333333333333
[ 2.62466929  2.94392029 10.87300429]
[ 3.          3.66666667 12.33333333]


In [72]:
# Q11. use `ceil` and `floor` to round up and down the values in the following array
arr = np.array([0.1, 0.8, -2.2, -9.87])
np.ceil(arr)

array([ 1.,  1., -2., -9.])

In [73]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [74]:
np.round(arr)

array([  0.,   1.,  -2., -10.])

In [76]:
# Q12. calculate the following trigonometric functions

sine_45 = np.sin(45 * np.pi / 180)
cosine_90 = np.cos(90 * np.pi / 180)
tangent_30 = np.tan(30 * np.pi / 180)

print(sine_45, cosine_90, tangent_30)

0.7071067811865476 6.123233995736766e-17 0.5773502691896257


In [78]:
# Q13. find elements from this array:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('shape of array is: ', arr.shape)
print('3rd element on 2nd row: ', arr[1, 2])
print('4th element on 1st row: ', arr[0, 3])
print('1st element on 2nd row: ', arr[1, 0])

shape of array is:  (2, 5)
3rd element on 2nd row:  80
4th element on 1st row:  40
1st element on 2nd row:  60


**Q14**: why is NumPy fast? (mention 1 out of the 3 reasons)

**Answer:**

1. Memory managemnet
1. Uses C underneath to do magic (compiled)
1. Vectorization (parallellism)
