# Exercises: NumPy

In [34]:
import numpy as np

In [35]:
# Consider the following nd-array:
arr = np.array([
    [ 1, 2, 3],
    [ 4, 5, 6],
    [ 7, 8, 9]])

In [36]:
# what is the number of dimensions?
print(f"number of dimensions is: {arr.ndim}")

# what is the size?

# what is the shape?

# what is the data type stored in the array? `hint: dtype`


number of dimensions is: 2


In [37]:
# find the index of the value 1
print(f"the index of the value 1 is: [0,0] since arr[0,0] = {arr[0,0]}")

# find the index of the value 5

# find the index of the value 9


the index of the value 1 is: [0,0] since arr[0,0] = 1


In [38]:
# extract the 3rd row

# extract the 1st and 2nd rows row


In [39]:
# add the 1st and last columns

# multiply the 2nd row by itself


In [40]:
# consider the following array:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

# what is the data type of the array?


In [41]:
#  reshape this 1D array into a 2D array of size (2, 5) (print the result)
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# use: the .reshape function

In [42]:
#  reshape this 2D array into a 1D array of size 9 (print the result)
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [43]:
#  flatten this 3D array into a 1D array
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])



In [44]:
# create an array of 15 elements
# hint: use `np.arange()`


# reshape it into a 3x5 array
# hint: use `reshape`


# reshape it again into a 5x3 array



In [45]:
# create a 3x4 array of zeros
# hint: use `np.zeros()`

# create a 3x4 array of ones
# hint: use `np.ones()`

# create a 3x4 array of 88s
# hint: use `np.full()`

Exercise: copy vs. view

In [46]:
# Explain the output of the following code:
arr_a = np.array([1, 2, 3])
arr_b = arr_a[:]
arr_b[0] = 4
print(arr_a)

[4 2 3]


Why is arr_a modified even though we only modified arr_b?

Answer: 

In [47]:
list_a = [1, 2, 3]
list_b = list_a[:]
list_b[0] = 4
print(list_a)

[1, 2, 3]


What do you notice about the difference between a Python list and a NumPy array? Specifically, one the `list_b = list_a[:]` assignment.

- is the list copied or viewed?
- is the array copied or viewed?

Answer: 

In [48]:
#  stack the following two 1D arrays such that the output is
# horizontally stacked: [1, 2, 3, 4, 5, 6]
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# use: np.hstack


In [49]:
#  stack the following two 1D arrays such that the output is
# vertically stacked: [[1, 2, 3],
#                      [4, 5, 6]]
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])




In [50]:
#  sort the following array in descending order
a = np.array([3, 2, 1, 4, 5])

# use: np.sort
# use: np.flip


In [51]:
# find the values in the array that are greater than 30
a = np.array([10, 20, 30, 40, 50])
print(a[a > 30])

#  find even numbers in the array
a = np.array([10, 20, 30, 40, 50])



[40 50]


In [52]:
# Consider the following ndarray:
arr = np.array([[4, 3, 2], [10, 1, 0], [5, 8, 24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [53]:
# Calculate the mean and std of values on the entire array


# Calculate the mean and std across the vertical axis
print(arr.std(axis=0))

# Calculate the mean and std across the horizontal axis


[ 2.62466929  2.94392029 10.87300429]


In [54]:
#  find the index of the maximum value in the array
arr = np.array([4, 3, 2, 10, 1, 0, 5, 8, 24])
# use: np.argmax

#  find the index of the minimum value in the array
# use: np.argmin


In [55]:
# use `ceil` and `floor` to round up and down the values in the following array
arr = np.array([0.1, 0.8, -2.2, -9.87])


In [56]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
# `hint: np.nonzero`


In [57]:
# Create a 3x3 identity matrix
# `hint: np.eye`


In [58]:
# Create a 3x3x3 array with random values
# `hint: np.random.random`
