# Linear Algebra

In [3]:
import numpy as np
from numpy import linalg # linear algebra

### 1D to 2D to 3D and beyond

Vector (1D) $x$ has length $n$, or has $n$ components:

$$x =\begin{bmatrix}x_{1}  \\ \vdots  \\x_{n}\end{bmatrix}$$

<img src="https://static.tutorialandexample.com/scipy/scipy-linear-algebra1.png">

In [4]:
x = np.array([10, 100])
print(x, x.shape)

[ 10 100] (2,)


### Understanding column-vectors, row-vectors, and just, vectors

In [ ]:
# the example below shows the difference between (1,6) and (6,) arrays, and then try a (6,1)
a = np.array([10, 100])
print(a, 'shape:', a.shape)
print('---')
b = np.array([[10, 100]])
print(b, 'shape:', b.shape)

[ 10 100] shape: (2,)
---
[[ 10 100]] shape: (1, 2)


In [ ]:
print(a + a, (a+a).shape)
print(b + b, (b+b).shape)

[ 20 200] (2,)
[[ 20 200]] (1, 2)


In [ ]:
print(a, 'shape:', a.shape)
print('---')
c = np.array([[10],
              [100]])
print(c, 'shape:', c.shape)

[ 10 100] shape: (2,)
---
[[ 10]
 [100]] shape: (2, 1)


In [ ]:
print(a + c)

[[ 20 110]
 [110 200]]


### Vector dot product

$$
x \cdot y = \sum_{i=1}^{n} x_i y_i = x_1 y_1 + \dots + x_n y_n
$$

In [ ]:
def dot_product(x, y):
    return sum(i * j for i, j in zip(x, y))

dot_product([3, 2, 6], [1, 7, -2])

5

In [ ]:
x = np.array([0, 1, 2])
y = np.array([9, 2, 5])
print(x @ y)
# print(np.dot(x, y)) # <-- same

12


### Vector Length (Norm)

Here is what `np.linalg.norm(v)` does to a vector `v`:

1. Square each element of the vector.
2. Sum up the squared values obtained in the first step.
3. Take the square root of the obtained sum to get the norm of the vector.


In [ ]:
vector_v = [3, -4, 5]
norm_result = np.linalg.norm(vector_v)
print("Euclidean norm of vector v:", norm_result)

Euclidean norm of vector v: 7.0710678118654755


The **$\ell_2$ norm** (Euclidean) which the method `norm` calculates, is expressed more generally as:

$$\|v\|_2 = \sqrt{v \cdot v} = \sqrt{\sum_{i=1}^n v_i^2}$$

### Matrix

Matrix (2D) $A$:

$$\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}$$

In [10]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [11]:
A * 10

array([[30, 40],
       [50, 60],
       [70, 80]])

## Transposing a Matrix

At times it is useful to pivot a matrix for conformability- that is in order to matrix divide or multiply, we need to switch the rows and column dimensions of matrices. Consider the matrix $A$:

$$
\begin{equation}
	A=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}	
\end{equation}
$$
The transpose of A (denoted as $A^{T}$) is
$$
\begin{equation}
   A^{T}=\begin{bmatrix}
	  a_{11} & a_{21} & a_{31} \\
	  a_{12} & a_{22} & a_{32} \\
	\end{bmatrix}_{2 \times 3}
\end{equation}
$$

The transpose of an $m \times n$ matrix is an $n \times m$ matrix.

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A = A.T
print(A)

[[1 4]
 [2 5]
 [3 6]]


### Broadcasting

Broadcasting vectorizes array operations, improving computational efficiency by utilizing C loops.

$$
\begin{equation}
	A+3=
	\begin{bmatrix}
	  a_{11}+3 & a_{12}+3 \\
	  a_{21}+3 & a_{22}+3 	
	\end{bmatrix}
\end{equation}
$$

$$
\begin{equation}
	3A=
	\begin{bmatrix}
	  3a_{11} & 3a_{12} \\
	  3a_{21} & 3a_{22} 	
	\end{bmatrix}
\end{equation}
$$

Read more about Broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html

### Addition

Addition and subtraction works the same:

\begin{equation}
	A + B =
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix} +
	\begin{bmatrix} b_{11} & b_{12} \\
	  b_{21} & b_{22}
	\end{bmatrix}
	=
	\begin{bmatrix}
	  a_{11}+b_{11} & a_{12}+b_{12} \\
	  a_{21}+b_{21} & a_{22}+b_{22} 	
	\end{bmatrix}
\end{equation}

### Element-wise multiplication

The element-wise multiplication of two matrices is also called the *Hadamard product*:

$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}
$$

**Note: when we say matrix multiplication we don't usually refer to element-wise multiplication, rather, to the dot product of two matrices (next section).**

In [ ]:
# Element-wise multiplication
A = np.array([[1, 2, 2], [1, 2, 2]])
B = np.array([[10, 20, 30], [40, 50, 60]])
A * B

array([[ 10,  40,  60],
       [ 40, 100, 120]])

### Matrix-matrix dot product

<img alt="animation of matrix multiplication" src="https://www.mscroggs.co.uk/img/full/multiply_matrices.gif" width="600">

<img alr="matrix muliplication" src="../assets/mmm.png" width="600">

In [ ]:
# Matrix-matrix multiplication (dot product)
A = np.array([[1, 2, 2], [1, 2, 2], [1, 2, 2]])
B = np.array([[10, 20, 30], [40, 50, 60], [40, 50, 60]])
print(A @ B)
# print(A.dot(B)) # <-- same

[[170 220 270]
 [170 220 270]
 [170 220 270]]


### Matrix-vector dot product

- Left-hand side is always interpreted as a transformation matrix.
- Right-hand side is always interpreted as vectors (stacked horizontally, if more than one)

One vector:

$$
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
a_{31} & a_{32}
\end{bmatrix}
\begin{bmatrix}
v_1 \\
v_2
\end{bmatrix}
=
\begin{bmatrix}
a_{11} v_{1} + a_{12} v_{2} \\
a_{21} v_{1} + a_{22} v_{2} \\
a_{31} v_{1} + a_{32} v_{2}
\end{bmatrix}
$$

Two vectors:

$$
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
a_{31} & a_{32}
\end{bmatrix}
\begin{bmatrix}
v_1 & u_1 \\
v_2 & u_2
\end{bmatrix}
=
\begin{bmatrix}
a_{11} v_{1} + a_{12} v_{2} & a_{11} u_{1} + a_{12} u_{2} \\
a_{21} v_{1} + a_{22} v_{2} & a_{21} u_{1} + a_{22} u_{2} \\
a_{31} v_{1} + a_{32} v_{2} & a_{31} u_{1} + a_{32} u_{2}
\end{bmatrix}
$$

In [ ]:
np.zeros((2, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((6, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Inverting a Matrix

As before, consider the square $2 \times 2$ matrix $A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22}\end{smallmatrix} \bigr)$.  Let the inverse of matrix A (denoted as $A^{-1}$) be 

$$
\begin{equation}
	M^{-1}=\begin{bmatrix}
             a & b \\
		     c & d 
           \end{bmatrix}^{-1}=\frac{1}{ad-bc}	\begin{bmatrix}
		             d & -b \\
				     -c & a 
		           \end{bmatrix}
\end{equation}
$$

The inverted matrix $A^{-1}$ has a useful property:
$$
\begin{equation}
	A A^{-1}=A^{-1} A=I
\end{equation}
$$

where $I$, the identity matrix (similar to $1$), is:
$$
\begin{equation}
	I =\begin{bmatrix}
             1 & 0 \\
		     0 & 1 
           \end{bmatrix}
\end{equation}
$$
furthermore, $A I = A$ and $I A = A$.

In [ ]:
A = np.array([[2, 4], [6, 8]])
print("A:")
print(A)
print("A inverse:")
print(np.linalg.inv(A))

A:
[[2 4]
 [6 8]]
A inverse:
[[-1.    0.5 ]
 [ 0.75 -0.25]]


A *Tensor*: is an array of n dimensions. So, a Vector and a Matrix are 1D and 2D Tensors, respectively.

Here is a 3D Tensor $T$:

$$
\mathbf{T} =
\begin{bmatrix}
    \begin{bmatrix}
    t_{111} & t_{121} & \dots  & t_{1m1} \\
    t_{112} & t_{122} & \dots  & t_{1m2} \\
    \vdots & \vdots & \ddots  & \vdots \\
    t_{11n} & t_{12n} & \dots  & t_{1mn}
\end{bmatrix}
\begin{bmatrix}
    
    t_{211} & t_{221} & \dots  & t_{2m1} \\
    t_{212} & t_{222} & \dots  & t_{2m2} \\
    \vdots & \vdots & \ddots  & \vdots \\
    t_{21n} & t_{22n} & \dots  & t_{2mn}
\end{bmatrix}
\end{bmatrix}
$$