# Exercises: Linear Algebra

- Add notes about scientific notation (students will see it when they do the inverse and don't see zeros!)
- Add notes about numerical problems (see question 8 About arccos, it did not accept the value because it fell out of its domain 1.0000000002)

<img src="https://www.wallstreetmojo.com/wp-content/uploads/2019/08/Scientific-Notation-in-Excel-Example1.3.png">

In [1]:
import numpy as np

In [2]:
# Element-wise multiplication
A = np.array([[1, 2, 2],
             [1, 2, 2]])
B = np.array([[10, 20, 30],
             [40, 50, 60]])
A * B

array([[ 10,  40,  60],
       [ 40, 100, 120]])

In [5]:
A.dot(B.T)

array([[110, 260],
       [110, 260]])

In [27]:
A @ B.T

array([[110, 260],
       [110, 260]])

**Vectors**


**Q1.** Let $\mathbf{v} = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$. Find the following:

- (a) $2\mathbf{v}$
- (b) $\frac{1}{2} \mathbf{v}$
- (c) $-\mathbf{v}$
- (e) $5 \mathbf{v} - \frac{1}{2} \mathbf{v}$

In [ ]:
# your code here...


**Q2.** Let $\mathbf{v} = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$ and $\mathbf{w} = \begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix}$. Find the following:

- (a) $\mathbf{v} + \mathbf{w}$
- (b) $\mathbf{v} - \mathbf{w}$
- (c) $3 \mathbf{v}$
- (d) $\|\mathbf{v}\|$
- (e) $\mathbf{v} \cdot \mathbf{w}$

In [ ]:
# your code here...

**Q3.** Let $\mathbf{u} = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$, $\mathbf{v} = \begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix}$, and $\mathbf{w} = \begin{pmatrix} 7 \\ 8 \\ 9 \end{pmatrix}$. Find the following:

- (a) $\mathbf{u} + \mathbf{v} + \mathbf{w}$
- (b) $2 \mathbf{u} - \mathbf{v}$
- (c) $3 \mathbf{u} \cdot \mathbf{v}$
- (d) $\|\mathbf{u} + \mathbf{v}\|$

In [ ]:
# your code here...

**Matrices**

**Q4.** Let $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$. Find the following:

- (a) $2A$
- (b) $\frac{1}{2} A$
- (c) $-A$

In [ ]:
# your code here...

**Q5.** Let $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$. Find the following:

- (a) $A + B$
- (b) $AB$
- (c) $A^T B^T$
- (d) $A^{-1} B^{-1}$

In [ ]:
# your code here...

**Q6.** Let $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$. Find the following:

- (a) $2B - 3A$
- (b) $B \odot A$
- (c) $A^T B^T$
- (d) $AA^{-1} + BB^{-1}$

In [ ]:
# your code here...

**Q7.** Let:

$A = \begin{pmatrix}
    1 & 2 \\
    6 & 3
\end{pmatrix}$ , 
$B = \begin{pmatrix}
    2 & 1 \\
    3 & 5
\end{pmatrix}$ , 
$\mathbf{v} = \begin{pmatrix} 2 \\ 3 \end{pmatrix}$ , 
$\mathbf{u} = \begin{pmatrix} 4 \\ 6 \end{pmatrix}$

Find the following:

- (a) $2A \mathbf{v}$
- (b) $-2B \mathbf{v}$
- (c) $AB\mathbf{u}$
- (D) $(A + B)(\mathbf{u} - 2\mathbf{v})$

In [ ]:
# your code here...

### Q8. Vector angle:

$$
\theta = \cos^{-1} \left( \frac{\vec{u} \cdot \vec{v}}{|\vec{u}||\vec{v}|} \right)
$$

In [12]:
# your code here...
import numpy as np

# Interesting discussion about numerical problems with small numbers here!
u = np.array([2, 3])
v = np.array([4, 6])

norms = np.linalg.norm(u) * np.linalg.norm(v)
dot = np.dot(u, v)
print(dot)
print(norms)
rounded = np.round(dot / norms)
print(np.arccos(rounded))

26
25.999999999999996
0.0


In [5]:
np.arccos?

Call signature:  np.arccos(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'arccos'>
File:            c:\users\thund\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
arccos(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Trigonometric inverse cosine, element-wise.

The inverse of `cos` so that, if ``y = cos(x)``, then ``x = arccos(y)``.

Parameters
----------
x : array_like
    `x`-coordinate on the unit circle.
    For real arguments, the domain is [-1, 1].
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
   